### ISSUE TITLE
CUDAExecutionProvider is not avaliable

### ISSUE THREAD

**Issue by indiejoseph** [Naozumi520/g2pW-Cantonese#1]
UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'

consider change onnxruntime to onnxruntime-gpu in requirements.txt, but the version is depends on Cuda and CuDNN version

**Comment by Naozumi520** [comment]
Oh. Thanks for pointing this out and your PR #2
Just merged! :D
